### ISSUE TITLE
Refreshing issue

### ISSUE THREAD

**Issue by MaLi812** [F4stFr3ddy/homebridge-jablotron-alarm#19]
Hi,
first I want to thank you for your awesome work, great plugin! The new 2.0.0 version works really fine with a minor issue on my Jablotron JA-100.
Overall I have 5 segments on my keyboard unit. I use one segment to arm and disarm the alarm and another segment to partially arm and disarm the alarm: 
"sections": [
                        {
                            "name": "Wohnhaus",
                            "segment_id": "STATE_1",
                            "segment_key": "section_1"
                        },
                        {
                            "name": "Intern",
                            "segment_id": "STATE_1",
                            "segment_key": "section_1",
                            "keyboard_key": "keyboard_2_3"
                        },
...
The issue i have is that if I arm my unit by keyboard, Homekit or Jablotron app, the state of the second section (name: "Intern", for partially arming) doesn't refresh. The state of the first section ("Wohnhaus") changes to "armed" (correct), but the second segment ("Intern") stays disarmed. 
![img_0518](https://user-images.githubusercontent.com/47432981/52650088-d8bc7d80-2ee9-11e9-802d-621203a082b3.jpeg)
In the prior version of this plugin the section "Intern" also changed to "armed. 
If I partially arm the alarm with section two, the state of this section changes to "at home" and refreshes the state of the first section also to "at home"
![img_0519](https://user-images.githubusercontent.com/47432981/52650363-66986880-2eea-11e9-9c9c-ab50d88941b8.jpeg) (correct behaviour)

Does anyone else has this issue?

Thanks in advance.

MaLi

**Comment by misncz** [comment]
You can’t have 2 sections with the same ID. For this define one section with keyboard_key ie keep only first section.

**Comment by MaLi812** [comment]
Ok, thx. The similar configuration worked absolutely fine in version 1.1.0, so I thought I would in 2.0.0 too.

**Comment by misncz** [comment]
Even in 1.1.0 it wasn't the correct configuration. There should be no duplicated sections defined - number of sections corresponds to the number of segments available on Jablotron unit. With version 2.0.0 it just became more visible because we changed the plugin from accessory- to platform- based to optimise network load and to deal better with automatic background refresh

**Comment by MaLi812** [comment]
"For this define one section with keyboard_key ie keep only second section and change its name to Wohnhaus. In Homekit setting it to Home would prtially arm it, Away fully arm it" I tried this in version 1.1.0 and in 2.0.0. --> State changes to "partially armed" regardless what setting I choose. If I choose the 'incorrect' configuration it works without issues in 1.1.0 and with the described 'refreshing issue' in 2.0. I'll do further testing and report any progress...

**Comment by misncz** [comment]
> "For this define one section with keyboard_key ie keep only second section and change its name to Wohnhaus. In Homekit setting it to Home would prtially arm it, Away fully arm it" I tried this in version 1.1.0 and in 2.0.0. --> State changes to "partially armed" regardless what setting I choose. If I choose the 'incorrect' configuration it works without issues in 1.1.0 and with the described 'refreshing issue' in 2.0. I'll do further testing and report any progress...

You are right - arm fully functionality (eg Away in Homekit) is not possible with keyboard_key configured. Jablotron API requires a different value to be passed to arm fully and different to arm partially. The fix will be published under version 2.0.1. The config stays the same, it's just internal handling of Jablotron API that will change

**Comment by MaLi812** [comment]
With version 2.0.1 installed I am able to fully arm und partially arm my unit in Homekit. The in the readme described config now works for me. 
Thx again for the plugin and for your immediate support! I'm very curious what comes next ;-)

**Comment by misncz** [comment]
> With version 2.0.1 installed I am able to fully arm und partially arm my unit in Homekit. The in the readme described config now works for me.
> Thx again for the plugin and for your immediate support! I'm very curious what comes next ;-)

Good to hear we made it working for you and fixed the issue I had missed originally. Enjoy the plugin!

**Comment by F4stFr3ddy** [comment]
@misncz great work and thanks for your commitment 😄

Next would be that we create a second alarm case where we utilize all states from Homekit plus make Homekit know when the alarm actually goes off. Last part will be tricky.
