### ISSUE TITLE
config helper run

### ISSUE THREAD

**Issue by markunca** [F4stFr3ddy/homebridge-jablotron-alarm#21]
Please any help how and where to run config-helper to get my informations?
Thank you

node config-helper.js m*****@gmail.com A*****c
^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OBmodule.js:549
    throw err;
    ^

Error: Cannot find module '/home/pi/config-helper.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by misncz** [comment]
Change directory to /usr/local/lib/node_modules/homebridge-jablotron and run it from there

@F4stFr3ddy Maybe we could add discovery mode into the plugin so that it would automatically detect services & accessories based on the config

**Comment by overflywingo** [comment]
Hello, I'm now running 2.01 ...but I can't locate  config-helper.js in /usr/local/lib/node_modules/homebridge-jablotron . ?

pi@raspberrypi:/ $ cd /usr/local/lib/node_modules/homebridge-jablotron
pi@raspberrypi:/usr/local/lib/node_modules/homebridge-jablotron $ ls
lib  LICENSE.txt  node_modules  package.json  README.md

**Comment by misncz** [comment]
Looks like it's missed in the packaging. We'll get this fixed ASAP. Meanwhile download it from https://github.com/F4stFr3ddy/homebridge-jablotron-alarm/blob/master/config-helper.js

Sorry for the inconvenience
