### ISSUE TITLE
Different values with config_helper

### ISSUE THREAD

**Issue by MaLi812** [F4stFr3ddy/homebridge-jablotron-alarm#24]
This might be an issue with the config_helper file:
The current version of config-helper gives back this keyboard-config:
name = Wohnhaus                                                                                                                                                                    
   segment_id = STATE_1                                                                                                                                                               
   segment_key = section_1                                                                                                                                                            
   keyboard_key = keyboard_2_5

the last version (delivered with 1.1.0) showed: 
name = Wohnhaus                                                                                                                                                                    
   segment_id = STATE_1                                                                                                                                                               
   segment_key = section_1                                                                                                                                                            
   keyboard_key = keyboard_2_3

With keyboard_key = keyboard_2_5 I'm unable to partially arm the unit, no issues with keyboard_key = keyboard_2_3.

Kind regards
MaLi

**Comment by misncz** [comment]
Looks like your Jablotron is configured a bit different way. My config comes with 3 sections where one of these supports partially armed state. Each section has one only keyboard assigned. I'd need your help to run modified config-helper.js tool to see what your Jablotron unit replies with when asked for keyboards
Upon downloading rename attached file to config-helper.txt to config-helper.js. Copy it over to PI to pi user home. After that copy it to homebridge-jablotron plugin using:
`sudo cp /home/pi/config-helper.js /usr/local/lib/node_modules/homebridge-jablotron/`

[config-helper.txt](https://github.com/F4stFr3ddy/homebridge-jablotron-alarm/files/2871886/config-helper.txt)

**Comment by MaLi812** [comment]
I'm using Docker on my NAS, so it worked a little different, but it worked i think ;-)
[config-helper.log](https://github.com/F4stFr3ddy/homebridge-jablotron-alarm/files/2871939/config-helper.log)

**Comment by misncz** [comment]
Thanks for the output! That's interesting really - you have 2 keyboards assigned to STATE_1 section (section_1) - keyboard_2_3 and keyboard_2_5. I have never seen this before - can you briefly describe how you can control your house (segment Wohnhaus)? Do you have 1 or 2 segments for Wohnhaus mounted on Jablotron unit? Or some additional button/switch that can control Wohnhaus segment? Maybe a screenshot from Jablotron iOS/Android app or MyJablotron website would help as well

**Comment by misncz** [comment]
I just had a quick call with friend who is Jablotron partner and he confirmed you can have the same segment mounted twice where one allows you to partially arm it and the other one to arm it fully. He said it's not standard setup because this can be achieved using single segment where single press on arm button arms partially and double press arms fully - this is what I have set up at home. I'll wait for your confirmation and modify the config helper tool to be able to deal with your setup as well

**Comment by misncz** [comment]
@MaLi812 attached you can find modified version of config-helper.js that should be able to detect your config as well. I tested it offline with the response log you had sent before and it worked as expected. Please try it online using your Jablotron account - once tested I'll promote it in new version

Do the same you did before (rename to config-helper.js, copy to NAS etc)

[config-helper.txt](https://github.com/F4stFr3ddy/homebridge-jablotron-alarm/files/2872244/config-helper.txt)

**Comment by MaLi812** [comment]
Yes, you're right. I've two keyboards assigned to STATE_1:
![bildschirmfoto 2019-02-16 um 19 02 10](https://user-images.githubusercontent.com/47432981/52903423-6d421b00-321d-11e9-9f25-1004ccbf9505.png)
(bootom to top):
1. Fully arm Wohnhaus
2. Panic alarm
3. partially arm Wohnhaus
4. Fully arm garage
5.  Open garage

I didn't know till now, that you can press the fully arm button twice for partially arming (and i even don't know if my Jablotron partner does :-))

I tested your new config_helper file. This is the (correct) output:

[config_helper_output.txt](https://github.com/F4stFr3ddy/homebridge-jablotron-alarm/files/2872255/config_helper_output.txt)

Thx for your awesome work!

**Comment by F4stFr3ddy** [comment]
Merged and published. Thanks for your help!

**Comment by misncz** [comment]
Cool, thanks for quick turnaround and testing effort! The output is what it should look like and is, as you say, correct now
Actually single press arms partially, double press arms fully. "Problem" with your setup is you paid extra money for something, 2nd Wohnhaus segment, you don't need really
