### ISSUE TITLE
error logging

### ISSUE THREAD

**Issue by MaLi812** [F4stFr3ddy/homebridge-jablotron-alarm#27]
Hi, its me again ;-)

First I thought I found an error while I was trying to partially arm my alarm system :

[37m[2/18/2019, 11:36:29 PM][39m [36m[Jablotron][39m Switching section section_1 (using keyboard_2_3) to new state: partialSet
[37m[2/18/2019, 11:36:32 PM][39m [36m[Jablotron][39m { status: false,
  error_status: 'bypass_dialog_blocked',
  checksum: '******',
  server_id: '*****-******',
  client_id: null }
[37m[2/18/2019, 11:36:32 PM][39m [36m[Jablotron][39m Error: bypass_dialog_blocked
    at /usr/local/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:25:31
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:56:17)

 I tried it several times, every time with the same error...
 After a while I realized that I caused this error by myself, because I left a window open while partially arming the unit. 
Would it be possible to integrate a more concise output for this error in homebridge.log in one of the future versions of the plugin? ( Only in case you need any suggestions for the future development...)

Kind regards
MaLi

**Comment by misncz** [comment]
Yes it is possible to provide a better handling in this particular case. Just wondering - what happened in Homekit after this error? Did it return to previous state?

**Comment by MaLi812** [comment]
After seveveral minutes of trying to set the new state, HomeKit returned to the previous state (Alarm off) without any further notifications.
