### ISSUE TITLE
How to do to have the Jablotron alarm appearing as a switch ? 

### ISSUE THREAD

**Issue by overflywingo** [F4stFr3ddy/homebridge-jablotron-alarm#28]
> The current setup of Jablotron as an Alarm System in Homekit requires user authentication when executing automations. For example when the first person arrives home, turn the alarm off. This will prompt a notification on your iOS device or watch asking if you want to execute this command.
> This works every time and has the added benefit of being more secure, alternatively it is possible to make the Jablotron alarm appear as a switch and then the automation will work without confirmation

Hi, sorry for my ignorance but can you explain what to do to have the Jablotron alarm appearing as a switch ?   Thanks

**Comment by misncz** [comment]
In the Homebridge config (config.json) define your alarm under "switches" instead of "sections". Note this way you'd lose partially armed state if available on your Jablotron unit

**Comment by F4stFr3ddy** [comment]
Originally it was just an idea, but thanks to @misncz brilliant implementation of switches its already possible. Tried it out today, works perfect, really happy with it!

**Comment by overflywingo** [comment]
Indeed switch is working well
Not an issue for me to have lost partial armed state as I'm  using just one
section for all my house. Nevertheless using switches I've lost the status
of alarm triggered....so no more possible to create scenario in such case.




Le 22 février 2019 à 23:41:52, Fred de Gier (notifications@github.com) a
écrit:

**Comment by F4stFr3ddy** [comment]
You can setup both as Alarm and Switch and use `refreshOnStateChange : true` this will give you notifications but won't ask you for automation confirmation (potential risk). 

Alarm triggered is not implemented yet, its probably a hard feature to implement but is on the backlog.
