### ISSUE TITLE
[question] mapping states differently

### ISSUE THREAD

**Issue by DarminDDR** [F4stFr3ddy/homebridge-jablotron-alarm#29]
Is it possible to remap the states in homekit to match different states of the Jablotron alarm?

Thank you very much for your time and your work.

**Comment by F4stFr3ddy** [comment]
Can you given an example of what you mean?

You can give whatever segment you want to each Homekit state and (dis)arm that, partial arm and disarm is also possible.

**Comment by misncz** [comment]
Just to note - Homekit comes with 4 states where 1 is of "disarmed" type = Off. The other 3 are of "armed" state - Home/Away/Night. This is important for automation
We could of course add the ability to change the mapping but Off needs to be mapped to disarmed state.
Answer the question raised by @F4stFr3ddy and we'll see what could be done here
