### ISSUE TITLE
Arming one thing arms everything

### ISSUE THREAD

**Issue by Patrik-svobodik** [F4stFr3ddy/homebridge-jablotron-alarm#30]
When I try to arm for example the garage, everything arms, I have a Arm everything section configured, but removed from Homebridge's config.json

**Comment by misncz** [comment]
Please provide your config.json and output of [config helper utility](url
https://github.com/F4stFr3ddy/homebridge-jablotron-alarm#Identify-Jablotron-services-and-devices) - mask out sensitive information (username & pwd & service ID)

**Comment by Patrik-svobodik** [comment]
I will tomorrow, I have to sleep, BTW aren’t you from Czech republic? Your username looks like it😀

**Comment by misncz** [comment]
Yes, I am ;-)
