### ISSUE TITLE
Status for different sensors

### ISSUE THREAD

**Issue by markunca** [F4stFr3ddy/homebridge-jablotron-alarm#31]
Hi guys, is also possible to get status from a different sensor like window sensors, motion sensors in some rooms etc. to run more different scene scenarios? It would be great to use current window sensor from jablotron which can stop heating in case the window is open.

**Comment by F4stFr3ddy** [comment]
Might be a cool addition, I'll see what we can retrieve from the system.

**Comment by F4stFr3ddy** [comment]
Closing this issue as it does not seem to be possible with the current API version.
