### ISSUE TITLE
Configuration Tool error

### ISSUE THREAD

**Issue by grzegorz914** [F4stFr3ddy/homebridge-jablotron-alarm#35]
Hi,

nice to see this plugin but I get error in log:

`Error: write EPROTO 3069483472:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2159`

any workaround?

Solved with:
`sed -i 's/TLSv1.2/TLSv1.0/g' /etc/ssl/openssl.cnf`

**Comment by F4stFr3ddy** [comment]
Seems like a config specific error, glad to hear you solved it! Enjoy.

**Comment by grzegorz914** [comment]
This fix working only with Node =< 10.16.2, Node 11 nad 12 get error.
