### ISSUE TITLE
Helper doesn't work

### ISSUE THREAD

**Issue by maaraneasi** [F4stFr3ddy/homebridge-jablotron-alarm#36]
Hi!

Thanks for the plugin!
I tried to set it up according to your readme but I hit an issue when using the helper:

```
/homebridge/node_modules/homebridge-jablotron # node config-helper.js user@emailsomething.com somepassword
/homebridge/node_modules/homebridge-jablotron/config-helper.js:38
                for (let i = 0; i < services.length; i++) {
                                             ^

TypeError: Cannot read property 'length' of undefined
    at /homebridge/node_modules/homebridge-jablotron/config-helper.js:38:46
    at /homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:20:17
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:56:17)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
/homebridge/node_modules/homebridge-jablotron #
```

Any idea what went wrong?

Thanks!!!

**Comment by F4stFr3ddy** [comment]
Will look into it and report back.

**Comment by F4stFr3ddy** [comment]
I just checked it and it works fine, which version of node are you using?

**Comment by maaraneasi** [comment]
I am running the docker image https://github.com/oznu/docker-homebridge
The version of node is 12.13.0
`/homebridge/node_modules/homebridge-jablotron # node --version
v12.13.0`

**Comment by F4stFr3ddy** [comment]
Trieed it with your node version, works here. Do you have internet connectivity? Running in docker?

**Comment by maaraneasi** [comment]
Yeah I am running directly in docker. The connectivity is fine and I can reach the jablotron's api from within the container:
`/homebridge/node_modules/homebridge-jablotron # ping api.jablonet.net
PING api.jablonet.net (194.169.224.30) 56(84) bytes of data.
64 bytes from 194.169.224.30 (194.169.224.30): icmp_seq=1 ttl=54 time=2.98 ms
64 bytes from 194.169.224.30 (194.169.224.30): icmp_seq=2 ttl=54 time=2.97 ms
64 bytes from 194.169.224.30 (194.169.224.30): icmp_seq=3 ttl=54 time=2.76 ms
^C
--- api.jablonet.net ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 3ms
rtt min/avg/max/mdev = 2.761/2.904/2.982/0.101 ms`

I tried from a regular os install (non-docker) a few weeks ago and ended up with the same error.

**Comment by maaraneasi** [comment]
actually, let me try one more thing....

**Comment by F4stFr3ddy** [comment]
Maybe its failing on a special character not being escaped properly?

**Comment by F4stFr3ddy** [comment]
Are you using this account also on your phone? It might be that if you just created this account you still need to verify it via the app / website.

**Comment by maaraneasi** [comment]
Yeah you are absolutely correct! I created the account only for this propose and it was waiting for the first login and to my agreement with the TOS.
Thanks for your help - its much appreciated!

**Comment by misncz** [comment]
The helper should be able to handle this without stacktrace and provide more meaningful msg to the users. We will provide a change that accomodates this fix

**Comment by F4stFr3ddy** [comment]
Someone else also reported this problem earlier, the code itself also crashes on it, so yes the helper but also the actual program should both detect this issue and log it.

**Comment by F4stFr3ddy** [comment]
Config has been updated.
