### ISSUE TITLE
Sensor

### ISSUE THREAD

**Issue by soylant** [F4stFr3ddy/homebridge-jablotron-alarm#38]
Hi

I have been using this with my Ja-100 alarm for almost a year now without any problems, I really love this 😄
Are there any chance to get the sensor status into homebridge ?
I am also running a Home Assistant on another PI and there I have my Jablotron sensor and all in.

**Comment by grzegorz914** [comment]
This will be very nice enhancement.

**Comment by F4stFr3ddy** [comment]
What kind of behavior would you like to see? Sensor as in open/close (on/off)?

**Comment by grzegorz914** [comment]
Hi,
I think for sensor always use open/close
open - activ
closed - inactiv

**Comment by F4stFr3ddy** [comment]
How are you getting the state of sensors on home assistant? With USB cable? So far I can't find them in the API.

**Comment by grzegorz914** [comment]
Homebridge>>>Openhab2>>>>S71200 PLC>>>JA-121T RS485

**Comment by F4stFr3ddy** [comment]
I see, well I have the parts to do it and actually have a working prototype to read from events from the BUS via USB. However, this plugin was designed to be working only with the API so it accessible for everyone who has a Jablotron alarm without further investments in hardware.

If you want we can work on a new plugin which reads the events in realtime, e.g. `homebridge-jablotron-bus` but without the sensors being in the API I don't see a way to integrate them in this plugin.

**Comment by soylant** [comment]
Hi 
Yes Ib HomeAssistant I got my PI connected through a USB to my Jablotron, I am using a addon from here https://github.com/plaksnor/HASS-JablotronSystem It is finding all my sensors but the problem is that don’t think they are working on this addon anymore and it is having some small problems, sometimes it is losing the sensors, but it is really cool when it is working, so today I am having both Homebridge and home assistant because I have your addon on homebridge and it is never failing 😄 so just thought maybe you could do the part with sensors 😄😄

**Comment by F4stFr3ddy** [comment]
Thanks, glad you like it. So we have 2 options:

1. Further investigate the API see if there is an option to read the sensors, this will never be realtime
2. Work on integrating the realtime bus into a separate plugin.

**Comment by soylant** [comment]
I would say number 2, maybe we can use some of the information on the link.. there is a huge thread all about sniffing the traffic between the sensors and Jablotron
