### ISSUE TITLE
JA-80?

### ISSUE THREAD

**Issue by markunca** [F4stFr3ddy/homebridge-jablotron-alarm#39]
Hi guys, with the New year, just quick question, any plan to bring also support for JA-80 during 2020?

**Comment by F4stFr3ddy** [comment]
Hi,

It does not currently work with JA-80? I only have JA-100 so I'm unable to test the JA-80. If you really want it you could grant me access to your system for an hour or 2 so I can sniff the app to find the differences between JA-80 and JA-100.

**Comment by markunca** [comment]
Hi,
from JA-80 it currently cannot see any section. Just send me your email address which I should grand access and you can try it - martin.kuncicky@gmail.com

**Comment by F4stFr3ddy** [comment]
After investigating it seems that Oasis only allows to control all sections at once via the app/api. We can however control segments and we can read the status of sections. The service_type is currently ja100 and needs to be changed to oasis in order to make it work. The rest seems to be all the same.

**Comment by markunca** [comment]
Just check it and it is working, thank you for fast support!

**Comment by F4stFr3ddy** [comment]
Well that's interesting as I haven't done anything yet :D what exactly is working?

**Comment by markunca** [comment]
As you wrote it needs to be changed in code, I tried to change it from ja100 to oasis in jablotron.js. But will wait for final change to have it working also after upgrade.

**Comment by F4stFr3ddy** [comment]
Ah that makes sense, I'll hopefully release the new version tomorrow. Thank you for your help!
