### ISSUE TITLE
identification parameters  Ja100 ans lan or wan dialogue

### ISSUE THREAD

**Issue by rikkta31** [F4stFr3ddy/homebridge-jablotron-alarm#47]
hello I had a question I wanted to know if the application communicate local on the LAN or with the jablotron cloud service.  a question other question I have trouble filling in the identification parameters what do I have as notification it is my connection parameters to my jablotron my email address is my password the second is the user of  the ja100 alarm center therefore a user
for the id of ​​the central is this the registration code
                        id": ????
                        "name": "Home",
                        "username": "??????,
                        "password": 
                       "passsword",
                        "pincode": "pincode",

merci

**Comment by F4stFr3ddy** [comment]
Hi,

It talks with the Jablotron cloud. 

You can use the `config-helper.js` to get the id etc. The username and password are the same as the one you use for the app.

**Comment by rikkta31** [comment]
bonjour et merci

j'utilise sur un raspberry cette application

hoobs
https://hoobs.org/
y a-t-il une méthode particulière pour la programmation désolé je suis
novice sur le sujet

merci
rikkta

Le mer. 1 avr. 2020 à 10:49, Fred de Gier <notifications@github.com> a
écrit :

**Comment by F4stFr3ddy** [comment]
Just login to the CLI and run (might need to adjust the path):
```
cd /usr/local/lib/node_modules/homebridge-jablotron
node config-helper.js username password
```

Change username for your Jablotron app username and password. 

Without that you can not retrieve your service id.

**Comment by rikkta31** [comment]
ok thanks


Le mer. 1 avr. 2020 à 15:21, Fred de Gier <notifications@github.com> a
écrit :
