### ISSUE TITLE
Dear Fredy,

### ISSUE THREAD

**Issue by jaroush1** [F4stFr3ddy/homebridge-jablotron-alarm#50]
sorry for bothering you but i am trying to get ID for my jablotron oasis 100, when i am using cd /usr/local/lib/node_modules/homebridge-jablotron its says that the directory is not exististing, i have followed your steps but somehow not able to get through, thx for your time and help jaromir

**Comment by F4stFr3ddy** [comment]
Hi,

This path depends on your OS, installation etc. You need to first know where your Homebridge package is installed. You can use `npm list -g` to list all your packages. This will result in a tree

```
/usr/local/lib
└─┬ npm@6.14.7
  ├── abbrev@1.1.1
```

Usually this is `/usr/local/lib/node_modules` on macOs and Linux.

**Comment by jaroush1** [comment]
perfect now i understood thank you
jaromir

**Comment by jaroush1** [comment]
Hello,
sorry to bother once again and hopefully for last time, i managed to find the folder but if i try to execute the node config-helper.js with the credentials it returns following 
{
 status: false,
 error_status: 'not_logged_in',
 checksum: '4e0a5f2250e13b14583a900483a182ab',
 server_id: '5335036-1599633373',
 client_id: null
}
Error: not_logged_in
   at /usr/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:25:31
   at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:57:21)
   at IncomingMessage.emit (events.js:327:22)
   at endReadableNT (_stream_readable.js:1220:12)
   at processTicksAndRejections (internal/process/task_queues.js:84:21)

user and password are correct was trying to access the website jablonet.net and no issue there, alarm is disarmed, i am using raspberry pi3, would you have idea what i am doing wrong? thx jaromir
