### ISSUE TITLE
jablotron oasis ID not logged in error

### ISSUE THREAD

**Issue by jaroush1** [F4stFr3ddy/homebridge-jablotron-alarm#52]
Hello,
sorry to bother once again and hopefully for last time, i managed to find the folder but if i try to execute the node config-helper.js with the credentials it returns following
{
status: false,
error_status: 'not_logged_in',
checksum: '4e0a5f2250e13b14583a900483a182ab',
server_id: 'xxxxxx',
client_id: null
}
Error: not_logged_in
at /usr/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:25:31
at IncomingMessage. (/usr/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:57:21)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (_stream_readable.js:1220:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)

user and password are correct was trying to access the website jablonet.net and no issue there, alarm is disarmed, i am using raspberry pi3, would you have idea what i am doing wrong? thx jaromir

**Comment by F4stFr3ddy** [comment]
Hij,

Are you using Jablotron Oasis or Jablotron 100?

**Comment by jaroush1** [comment]
oasis

**Comment by F4stFr3ddy** [comment]
Did you add the option `-O` to the command as written in the README?

**Comment by jaroush1** [comment]
> Did you add the option `-O` to the command as written in the README?

yes i did same issue

**Comment by F4stFr3ddy** [comment]
Given that I do not have an Oasis system I can not debug or replicate your situation. If you want you can create an account on your system for me and I can debug the code.

**Comment by jaroush1** [comment]
sure it was also my thought i just didint want to bother you, do you have an email which i can use to create an account?

**Comment by F4stFr3ddy** [comment]
You can send an email to f4stfr3ddy@gmail.com so we can discuss the details.

**Comment by F4stFr3ddy** [comment]
Problem was tied to user, either permissions or not accepting the agreement. With different user it works. Closing
