### ISSUE TITLE
Trigger alarm with other sensors

### ISSUE THREAD

**Issue by iwanvandaele** [F4stFr3ddy/homebridge-jablotron-alarm#53]
Is it possible to trigger the alarm with other non jablotron sensors?
Set a swith on 1 and that the alarm starts?

Thx for the info.

Regards,
Iwan Vandaele

**Comment by F4stFr3ddy** [comment]
Yes, for example I am using Philips Hue Tap and have set in Homekit that button 1 will set the Jablotron to away.

**Comment by iwanvandaele** [comment]
I mean that the alarm starts to sound, when a other sensor has detected something

**Comment by F4stFr3ddy** [comment]
Yes that is possible but you need Jablotron hardware e.g. JA-114HN

Connect your switch to it and then program Jablotron to trigger the sirene. 

Triggering the sirene from this application in Homekit is not possible.

**Comment by iwanvandaele** [comment]
ok thx for the info

Regards,
Iwan Vandaele

**Comment by misncz** [comment]
You can switch on the sirene itself (without triggering proper alarm though). You just need to have sirene PGM configured - it's returned by config-helper.js in "switches" section. This config you can then apply in your homebridge config and define sirene as switch or outlet:

`					"sections": [
						{
							"name": "House",
							"segment_id": "STATE_1",
							"segment_key": "section_1",
							"keyboard_key": "keyboard_2_21822705"
						},
						{
							"name": "Cellar",
							"segment_id": "STATE_2",
							"segment_key": "section_2"
						},
						{
							"name": "Terrace",
							"segment_id": "STATE_3",
							"segment_key": "section_3"
						}
					],
					"switches": [
						{
							"name": "Hooter",
							"segment_id": "PGM_1",
							"segment_key": "pgm_1"
						}
					],
					"outlets": [
						{
							"name": "Camera",
							"segment_id": "PGM_2",
							"segment_key": "pgm_2"
						}
					]
`
